In [1]:
import numpy as np
import pandas as pd

# Group BY

In [2]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name="ERPData") #Importing DataSet

In [3]:
grp1=df.groupby("MaterialID") # Creating Gropus Based on Material ID

In [6]:
grp1.groups #Displaying the Gropus that are created

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [8]:
grp1.get_group("SDRT-67").reset_index(drop=True) #Displayiing group "SDRT-67

  MaterialID Location  Quantity
0    SDRT-67    MWH-1        34
1    SDRT-67    MWH-4        58
2    SDRT-67    MWH-5        12
3    SDRT-67    MWH-5       102
4    SDRT-67    MWH-1        57
5    SDRT-67    MWH-2        31

In [10]:
grp1.Quantity.agg("sum") #Finding Sum of the quantity based on each Material ID

MaterialID
AXCP-78    898
DDBN-89    383
GCVB-79    182
LXCV-21    243
SDRT-67    294
TMI-43T    885
Name: Quantity, dtype: int64

In [11]:
grp2=df.groupby(["Location","MaterialID"]) # Creating Group based on 2 column

In [12]:
grp2.groups

{('MWH-1', 'AXCP-78'): [1, 24, 25, 39, 48], ('MWH-1', 'DDBN-89'): [26, 40, 49], ('MWH-1', 'SDRT-67'): [10, 41], ('MWH-1', 'TMI-43T'): [9], ('MWH-2', 'AXCP-78'): [46], ('MWH-2', 'DDBN-89'): [45], ('MWH-2', 'GCVB-79'): [8, 15, 35, 36], ('MWH-2', 'LXCV-21'): [2], ('MWH-2', 'SDRT-67'): [42], ('MWH-2', 'TMI-43T'): [7], ('MWH-3', 'AXCP-78'): [47], ('MWH-3', 'DDBN-89'): [43], ('MWH-3', 'LXCV-21'): [44], ('MWH-3', 'TMI-43T'): [14], ('MWH-4', 'AXCP-78'): [4], ('MWH-4', 'DDBN-89'): [22, 30], ('MWH-4', 'SDRT-67'): [11], ('MWH-4', 'TMI-43T'): [0, 5, 6, 12, 13, 18, 19, 20, 21, 31, 32], ('MWH-5', 'AXCP-78'): [3, 37, 38], ('MWH-5', 'DDBN-89'): [23], ('MWH-5', 'GCVB-79'): [34], ('MWH-5', 'LXCV-21'): [27, 28, 29], ('MWH-5', 'SDRT-67'): [16, 17], ('MWH-5', 'TMI-43T'): [33]}

In [21]:
grp2.Quantity.agg("sum")

Location  MaterialID
MWH-1     AXCP-78       548
          DDBN-89       130
          SDRT-67        91
          TMI-43T       120
MWH-2     AXCP-78        85
          DDBN-89        69
          GCVB-79       156
          LXCV-21        27
          SDRT-67        31
          TMI-43T        29
MWH-3     AXCP-78        29
          DDBN-89        38
          LXCV-21        42
          TMI-43T        65
MWH-4     AXCP-78        36
          DDBN-89        75
          SDRT-67        58
          TMI-43T       559
MWH-5     AXCP-78       200
          DDBN-89        71
          GCVB-79        26
          LXCV-21       174
          SDRT-67       114
          TMI-43T       112
Name: Quantity, dtype: int64

In [38]:
newdf=grp2.agg(["sum","mean","size"]) #Finding the sum , Size , mean based on the groups
newdf

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1
MWH-3    AXCP-78          29   29.000000    1
         DDBN-89          38   38.000000    1
         LXCV-21          42   42.000000    1
         TMI-43T          65   65.000000    1
MWH-4    AXCP-78          36   36.000000    1
         DDBN-89          75   37.500000    2
         SDRT-67          58   58.000000    1
         TMI-43T         559   50.818182   11
MWH-5    AXCP-78         200   66.666667    3
         DDBN-89          71   71.000000    1
         GCVB-79          26   26.000000    1
         LXCV-21         174   58.000000    3
         SDRT-67         114   57.000000    2
         TMI-43T         112  112.000000    1

In [42]:
newdf.loc[["MWH-1","MWH-2","MWH-3"]] #Extracting the info of location and Material Id based on Quantity

                    Quantity
                         sum        mean size
Location MaterialID
MWH-1    AXCP-78         548  109.600000    5
         DDBN-89         130   43.333333    3
         SDRT-67          91   45.500000    2
         TMI-43T         120  120.000000    1
MWH-2    AXCP-78          85   85.000000    1
         DDBN-89          69   69.000000    1
         GCVB-79         156   39.000000    4
         LXCV-21          27   27.000000    1
         SDRT-67          31   31.000000    1
         TMI-43T          29   29.000000    1
MWH-3    AXCP-78          29   29.000000    1
         DDBN-89          38   38.000000    1
         LXCV-21          42   42.000000    1
         TMI-43T          65   65.000000    1

# Sorting on DataFrames

In [58]:
df_asc=df.sort_values("Quantity") #Ascending Order
df_asc.head()

   MaterialID Location  Quantity
8     GCVB-79    MWH-2        10
16    SDRT-67    MWH-5        12
34    GCVB-79    MWH-5        26
2     LXCV-21    MWH-2        27
30    DDBN-89    MWH-4        27

In [49]:
df_desc=df.sort_values("Quantity",ascending=False) #Descending Order
df_desc.head()

   MaterialID Location  Quantity
24    AXCP-78    MWH-1       152
39    AXCP-78    MWH-1       145
9     TMI-43T    MWH-1       120
33    TMI-43T    MWH-5       112
25    AXCP-78    MWH-1       109

In [56]:
df_sort_cols=df.sort_values(["MaterialID","Location","Quantity",]) #Sorting has been done based on the multiple cols in order of the column given
df_sort_cols.head()

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
48    AXCP-78    MWH-1        75
25    AXCP-78    MWH-1       109
39    AXCP-78    MWH-1       145
24    AXCP-78    MWH-1       152

In [57]:
df_sort_cols=df.sort_values(["MaterialID","Location","Quantity",],ascending=[True,False,True])
df_sort_cols.head() #Same as above but MaterialID, Quantity is in Ascending order and location is in Descending order

   MaterialID Location  Quantity
3     AXCP-78    MWH-5        65
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
4     AXCP-78    MWH-4        36
47    AXCP-78    MWH-3        29

# Merging the DataFrames

In [59]:
pune=pd.read_excel("CDAC_DataBook.xlsx" ,sheet_name="Pune")
mumbai=pd.read_excel("CDAC_DataBook.xlsx" ,sheet_name="Mumbai")

In [62]:
pune

      Name      Subject Grade
0   Rakesh       Python     A
1    Manoj     MLPython     C
2  Vaibhav   Statistics     B
3   Hitesh   CommSkills     A
4   Suyash  ProjectMgmt     B
5    Vinod           AI     B

In [63]:
mumbai

       Name     Subject Grade
0   Vaibhav   Six Sigma     A
1   Deepika  Statistics     B
2     Arjun  CommSkills     A
3    Chetan      Python     A
4  Abhishek    MLPython     B
5     Vinod          AI     C

In [69]:
pd.merge(pune,mumbai) # this will show empty dataframe because there is no entire common row in both the dataframe
#label and index may not be the same

Empty DataFrame
Columns: [Name, Subject, Grade]
Index: []

In [80]:
pd.merge(pune,mumbai,on="Subject" ) # merging the Pune and Mumbai based on Subject  
#common subject between Pune , Mumbai      ## By default how= inner

    Name_x     Subject Grade_x    Name_y Grade_y
0   Rakesh      Python       A    Chetan       A
1    Manoj    MLPython       C  Abhishek       B
2  Vaibhav  Statistics       B   Deepika       B
3   Hitesh  CommSkills       A     Arjun       A
4    Vinod          AI       B     Vinod       C

In [91]:
pd.merge(pune,mumbai,on=["Subject","Grade"],how="inner") #this will give all common cols in both tables

    Name_x     Subject Grade   Name_y
0   Rakesh      Python     A   Chetan
1  Vaibhav  Statistics     B  Deepika
2   Hitesh  CommSkills     A    Arjun

In [99]:
pd.merge(pune,mumbai,on="Subject",how="outer")

    Name_x      Subject Grade_x    Name_y Grade_y
0    Vinod           AI       B     Vinod       C
1   Hitesh   CommSkills       A     Arjun       A
2    Manoj     MLPython       C  Abhishek       B
3   Suyash  ProjectMgmt       B       NaN     NaN
4   Rakesh       Python       A    Chetan       A
5      NaN    Six Sigma     NaN   Vaibhav       A
6  Vaibhav   Statistics       B   Deepika       B

In [100]:
pd.merge(pune,mumbai,on="Subject",how="left")

    Name_x      Subject Grade_x    Name_y Grade_y
0   Rakesh       Python       A    Chetan       A
1    Manoj     MLPython       C  Abhishek       B
2  Vaibhav   Statistics       B   Deepika       B
3   Hitesh   CommSkills       A     Arjun       A
4   Suyash  ProjectMgmt       B       NaN     NaN
5    Vinod           AI       B     Vinod       C

In [101]:
pd.merge(pune,mumbai,on="Subject",how="right")

    Name_x     Subject Grade_x    Name_y Grade_y
0      NaN   Six Sigma     NaN   Vaibhav       A
1  Vaibhav  Statistics       B   Deepika       B
2   Hitesh  CommSkills       A     Arjun       A
3   Rakesh      Python       A    Chetan       A
4    Manoj    MLPython       C  Abhishek       B
5    Vinod          AI       B     Vinod       C