In [2]:
import numpy as np
import pandas as pddf
from numpy import random

In [3]:
df=pd.read_excel("CDAC_DataBook.xlsx", sheet_name="ERPData")

In [4]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [7]:
x1=df.MaterialID

In [11]:
len(np.unique(x1,return_counts=True))

2

In [13]:
np.unique(x1,return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [21]:
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
LXCV-21     5
GCVB-79     5
Name: count, dtype: int64

In [18]:
df1=x1.value_counts().reset_index()

In [19]:
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    LXCV-21      5
5    GCVB-79      5

In [26]:
df1["Proportion"]=df1['count']/sum(df1['count']) #Caluculating the proportions for cateorical data
df1

  MaterialID  count  Proportion
0    TMI-43T     15        0.30
1    AXCP-78     11        0.22
2    DDBN-89      8        0.16
3    SDRT-67      6        0.12
4    LXCV-21      5        0.10
5    GCVB-79      5        0.10

In [30]:
df1["pct"]=df1["Proportion"]*100
df1

  MaterialID  count  Proportion   pct
0    TMI-43T     15        0.30  30.0
1    AXCP-78     11        0.22  22.0
2    DDBN-89      8        0.16  16.0
3    SDRT-67      6        0.12  12.0
4    LXCV-21      5        0.10  10.0
5    GCVB-79      5        0.10  10.0

In [32]:
df1["cumsum"]=np.cumsum(df1['pct'])
df1

  MaterialID  count  Proportion   pct  cumsum
0    TMI-43T     15        0.30  30.0    30.0
1    AXCP-78     11        0.22  22.0    52.0
2    DDBN-89      8        0.16  16.0    68.0
3    SDRT-67      6        0.12  12.0    80.0
4    LXCV-21      5        0.10  10.0    90.0
5    GCVB-79      5        0.10  10.0   100.0

In [48]:
df1.sort_values("MaterialID")
df1.sort_index()

  MaterialID  count  Proportion   pct  cumsum
0    TMI-43T     15        0.30  30.0    30.0
1    AXCP-78     11        0.22  22.0    52.0
2    DDBN-89      8        0.16  16.0    68.0
3    SDRT-67      6        0.12  12.0    80.0
4    LXCV-21      5        0.10  10.0    90.0
5    GCVB-79      5        0.10  10.0   100.0

In [59]:
x=np.array([3,4,5,6])
f=np.array([20,18,9,12])
sum(x*f/sum(f)) #Finding Mean

np.float64(4.220338983050848)